# Generated by Django 5.1.7 on 2025-08-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Emp',
        ),
    ]
